#!/usr/bin/env python3
"""Reject reviewer edits to machine-owned catalog fields."""

from __future__ import annotations

import argparse
import subprocess
import sys
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from typing import Any

import yaml

EDITABLE_FIELDS = frozenset({"name", "description", "documentation"})
# The domain files hold the reviewable entry; the root sidecar holds every field
# the pipeline owns for the same names. Both are compared, because a machine-owned
# value is protected by nothing if the file carrying it is never selected.
DOMAIN_PATHSPEC = "standard_names"
SIDECAR_PATHSPEC = "catalog.yml"
CATALOG_PATHSPECS: tuple[str, ...] = (DOMAIN_PATHSPEC, SIDECAR_PATHSPEC)
# The sidecar is one mapping of release metadata for the whole export, and the
# block inside it that carries one element per reviewed name is the only place a
# name appears there; a violation in it is reported against that name rather
# than against the file.
PER_NAME_BLOCK_KEYS = frozenset({"review_batch"})
AUTHORITY_MESSAGE = (
    "This value is taken from the Data Dictionary or generated by the pipeline "
    "rather than authored; revert it."
)


@dataclass(frozen=True)
class CatalogFile:
    """One catalog file in either shape the export writes.

    A domain file is a list of entry mappings, so it fills ``entries`` and the
    blank-line record that keeps the entries visually separated. The root
    sidecar is a single mapping of release metadata instead, so it fills
    ``manifest`` and carries no entries.
    """

    entries: list[dict[str, Any]]
    blank_before: tuple[bool, ...]
    manifest: dict[str, Any] | None = None


@dataclass(frozen=True)
class Violation:
    path: str
    identity: str
    field: str
    base: Any
    head: Any

    def annotation(self) -> str:
        message = (
            f"{self.identity}: machine-owned field {self.field!r} changed; "
            f"base={self.base!r}; head={self.head!r}. {AUTHORITY_MESSAGE}"
        )
        return f"::error file={self.path}::{message}"


def _git(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        check=check,
        text=True,
        capture_output=True,
    )


def changed_catalog_paths(base: str, head: str) -> list[str]:
    result = _git(
        "diff",
        "--name-only",
        "--diff-filter=ACMRD",
        base,
        head,
        "--",
        *CATALOG_PATHSPECS,
    )
    return [line for line in result.stdout.splitlines() if line.endswith(".yml")]


def read_revision(path: str, revision: str) -> str | None:
    result = _git("show", f"{revision}:{path}", check=False)
    if result.returncode == 0:
        return result.stdout
    if (
        "does not exist" in result.stderr
        or "exists on disk, but not in" in result.stderr
    ):
        return None
    raise RuntimeError(result.stderr.strip())


def load_catalog(text: str | None, path: str) -> CatalogFile:
    if text is None or (loaded := yaml.safe_load(text)) is None:
        return CatalogFile(entries=[], blank_before=())
    if isinstance(loaded, Mapping):
        return CatalogFile(entries=[], blank_before=(), manifest=dict(loaded))
    if not isinstance(loaded, list) or not all(
        isinstance(item, dict) for item in loaded
    ):
        raise ValueError(
            f"{path}: catalog file must contain a list of entry mappings "
            f"or a mapping of release metadata"
        )
    entries: list[dict[str, Any]] = loaded

    starts = [
        index
        for index, line in enumerate(text.splitlines())
        if line.startswith("- name:")
    ]
    if len(starts) != len(entries):
        raise ValueError(
            f"{path}: every entry must begin with a top-level '- name:' key"
        )
    lines = text.splitlines()
    blank_before = tuple(index > 0 and not lines[index - 1].strip() for index in starts)
    return CatalogFile(entries=entries, blank_before=blank_before)


def _freeze(value: Any) -> Any:
    if isinstance(value, Mapping):
        return tuple(sorted((key, _freeze(item)) for key, item in value.items()))
    if isinstance(value, Sequence) and not isinstance(value, str | bytes):
        return tuple(_freeze(item) for item in value)
    return value


def _machine_signature(entry: Mapping[str, Any]) -> Any:
    return _freeze(
        {key: value for key, value in entry.items() if key not in EDITABLE_FIELDS}
    )


def _identity(base: Mapping[str, Any], head: Mapping[str, Any]) -> str:
    before = str(base.get("name", "<unnamed>"))
    after = str(head.get("name", "<unnamed>"))
    return after if before == after else f"{before} -> {after}"


def _join(path: str, key: str | int) -> str:
    if isinstance(key, int):
        return f"{path}[{key}]"
    return f"{path}.{key}" if path else key


def _value_diffs(
    base: Any,
    head: Any,
    path: str = "",
    editable: frozenset[str] = EDITABLE_FIELDS,
) -> Iterable[tuple[str, Any, Any]]:
    if isinstance(base, Mapping) and isinstance(head, Mapping):
        keys = list(base)
        keys.extend(key for key in head if key not in base)
        for key in keys:
            if not path and key in editable:
                continue
            field = _join(path, key)
            if key not in base:
                yield field, "<missing>", head[key]
            elif key not in head:
                yield field, base[key], "<missing>"
            else:
                yield from _value_diffs(base[key], head[key], field, editable)
        return
    if (
        isinstance(base, Sequence)
        and isinstance(head, Sequence)
        and not isinstance(base, str | bytes)
        and not isinstance(head, str | bytes)
    ):
        if len(base) != len(head):
            yield path, base, head
            return
        for index, (before, after) in enumerate(zip(base, head, strict=True)):
            yield from _value_diffs(before, after, _join(path, index), editable)
        return
    if base != head:
        yield path, base, head


def _key_order_diffs(
    base: Any, head: Any, path: str = "", root_label: str = "<entry>"
) -> Iterable[tuple[str, Any, Any]]:
    if isinstance(base, Mapping) and isinstance(head, Mapping):
        if set(base) == set(head) and list(base) != list(head):
            yield f"{path or root_label}.<key-order>", list(base), list(head)
        for key in base.keys() & head.keys():
            yield from _key_order_diffs(base[key], head[key], _join(path, key))
        return
    if (
        isinstance(base, Sequence)
        and isinstance(head, Sequence)
        and not isinstance(base, str | bytes)
        and not isinstance(head, str | bytes)
    ):
        for index, (before, after) in enumerate(zip(base, head)):
            yield from _key_order_diffs(before, after, _join(path, index))


def _manifest_identity(field: str, base: Any, head: Any) -> str:
    """Name a sidecar violation after the reviewed name it concerns.

    Nothing in the sidecar is authored, so the only distinction that helps a
    reviewer is whether the change lands in the block carrying one element per
    reviewed name or in the release metadata around it. A block keyed by name
    puts the name in the field path; a block listing names puts it in the value.
    """
    root, _, remainder = field.partition(".")
    key, bracket, _ = root.partition("[")
    if key not in PER_NAME_BLOCK_KEYS:
        return "<catalog>"
    if not bracket:
        return remainder.partition(".")[0].split("[", 1)[0] or "<catalog>"
    for value in (base, head):
        if isinstance(value, str):
            return value
    return "<catalog>"


def compare_manifests(
    path: str, base: dict[str, Any] | None, head: dict[str, Any] | None
) -> list[Violation]:
    """Compare the sidecar, every field of which the export owns.

    An export that first publishes the sidecar is additive, exactly as a first
    domain file is, so an absent base yields nothing to protect.
    """
    if not base:
        return []
    if not head:
        return [Violation(path, "<catalog>", "<catalog-present>", base, "<removed>")]
    diffs = [
        *_key_order_diffs(base, head, root_label="<catalog>"),
        *_value_diffs(base, head, editable=frozenset()),
    ]
    return [
        Violation(path, _manifest_identity(field, old, new), field, old, new)
        for field, old, new in diffs
    ]


def compare_catalogs(
    path: str, base: CatalogFile, head: CatalogFile
) -> list[Violation]:
    if base.manifest is not None or head.manifest is not None:
        return compare_manifests(path, base.manifest, head.manifest)

    violations: list[Violation] = []
    paired: dict[int, int] = {}
    used_head: set[int] = set()

    head_names = {
        entry.get("name"): index
        for index, entry in enumerate(head.entries)
        if isinstance(entry.get("name"), str)
    }
    for base_index, entry in enumerate(base.entries):
        head_index = head_names.get(entry.get("name"))
        if head_index is not None and head_index not in used_head:
            paired[base_index] = head_index
            used_head.add(head_index)

    for base_index, entry in enumerate(base.entries):
        if base_index in paired:
            continue
        signature = _machine_signature(entry)
        candidates = [
            index
            for index, candidate in enumerate(head.entries)
            if index not in used_head and _machine_signature(candidate) == signature
        ]
        if len(candidates) == 1:
            paired[base_index] = candidates[0]
            used_head.add(candidates[0])

    for base_index, entry in enumerate(base.entries):
        if base_index not in paired:
            identity = str(entry.get("name", f"entry[{base_index}]"))
            violations.append(
                Violation(path, identity, "<entry-present>", entry, "<removed>")
            )

    ordered_pairs = sorted(paired.items())
    head_order = [head_index for _, head_index in ordered_pairs]
    if head_order != sorted(head_order):
        violations.append(
            Violation(
                path,
                "<catalog>",
                "<entry-order>",
                [base.entries[index].get("name") for index, _ in ordered_pairs],
                [head.entries[index].get("name") for index in head_order],
            )
        )

    for base_index, head_index in ordered_pairs:
        before = base.entries[base_index]
        after = head.entries[head_index]
        identity = _identity(before, after)
        for field, old, new in _key_order_diffs(before, after):
            violations.append(Violation(path, identity, field, old, new))
        for field, old, new in _value_diffs(before, after):
            violations.append(Violation(path, identity, field, old, new))

    for (left_base, left_head), (right_base, right_head) in zip(
        ordered_pairs,
        ordered_pairs[1:],
    ):
        if right_base != left_base + 1 or right_head != left_head + 1:
            continue
        if base.blank_before[right_base] and not head.blank_before[right_head]:
            identity = str(head.entries[right_head].get("name", f"entry[{right_head}]"))
            violations.append(
                Violation(
                    path,
                    identity,
                    "<entry-separation>",
                    "blank line",
                    "no blank line",
                )
            )
    return violations


def run(base_revision: str, head_revision: str) -> list[Violation]:
    violations: list[Violation] = []
    for path in changed_catalog_paths(base_revision, head_revision):
        before = load_catalog(read_revision(path, base_revision), path)
        after = load_catalog(read_revision(path, head_revision), path)
        violations.extend(compare_catalogs(path, before, after))
    return violations


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", required=True, help="base commit to compare")
    parser.add_argument("--head", required=True, help="head commit to compare")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        violations = run(args.base, args.head)
    except (RuntimeError, ValueError, yaml.YAMLError) as error:
        print(f"::error::{error}")
        return 2
    for violation in violations:
        print(violation.annotation())
    if violations:
        print(
            f"Review edit guard found {len(violations)} machine-owned or structural change(s)."
        )
        return 1
    print(
        "Review edit guard passed: reviewer changes are confined to authored prose or names."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
