from __future__ import annotations

import importlib.util
import subprocess
import sys
import unittest
from pathlib import Path
from unittest.mock import patch

MODULE_PATH = Path(__file__).with_name("review_edit_guard.py")
SPEC = importlib.util.spec_from_file_location("review_edit_guard", MODULE_PATH)
assert SPEC is not None and SPEC.loader is not None
guard = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = guard
SPEC.loader.exec_module(guard)


def catalog(*entries: str) -> str:
    return "\n\n".join(entry.strip() for entry in entries) + "\n"


ENTRY_PATH = "standard_names/equilibrium.yml"

# The per-name block of the catalog manifest lives beside the domain files and
# carries every field the pipeline owns, so the reviewable entry holds only the
# name, the two prose fields, and the unit that gives them physical context.
SIDECAR_PATH = "catalog.yml"

ENTRY = """
- name: electron_density
  description: Electron density.
  documentation: Authored documentation.
  unit: m^-3
"""

SECOND_ENTRY = """
- name: electron_temperature
  description: Electron temperature.
  documentation: Authored documentation.
  unit: eV
"""

SIDECAR_ENTRY = """
- name: electron_density
  kind: scalar
  status: active
  physics_domain: equilibrium
  links: []
  arguments:
  - name: density
    operator: electron
    operator_kind: population
  sources:
  - kind: imas-dd
    ref: core_profiles/profiles_1d/electrons/density
    version: 4.1.0
"""


class ReviewEditGuardTests(unittest.TestCase):
    def compare(self, before: str, after: str, path: str = ENTRY_PATH):
        return guard.compare_catalogs(
            path,
            guard.load_catalog(before, "base"),
            guard.load_catalog(after, "head"),
        )

    def compare_sidecar(self, before: str, after: str):
        return self.compare(before, after, path=SIDECAR_PATH)

    def test_authored_fields_may_change(self):
        after = ENTRY.replace("electron_density", "free_electron_density", 1)
        after = after.replace("Electron density.", "Free-electron density.")
        after = after.replace(
            "Authored documentation.", "Expanded authored documentation."
        )
        self.assertEqual(self.compare(catalog(ENTRY), catalog(after)), [])

    def test_new_entry_is_allowed(self):
        self.assertEqual(self.compare("", catalog(ENTRY)), [])

    def test_changed_catalog_paths_selects_yaml_below_standard_names(self):
        result = subprocess.CompletedProcess(
            args=[],
            returncode=0,
            stdout="standard_names/equilibrium.yml\nstandard_names/README.md\n",
            stderr="",
        )
        with patch.object(guard, "_git", return_value=result) as git:
            self.assertEqual(
                guard.changed_catalog_paths("base", "head"),
                ["standard_names/equilibrium.yml"],
            )
        self.assertEqual(git.call_args.args[-1], "standard_names")

    def test_unit_change_names_identity_field_and_values(self):
        violations = self.compare(
            catalog(ENTRY), catalog(ENTRY.replace("unit: m^-3", "unit: eV"))
        )
        self.assertEqual(
            [(item.identity, item.field, item.base, item.head) for item in violations],
            [("electron_density", "unit", "m^-3", "eV")],
        )
        self.assertIn(
            "Data Dictionary or generated by the pipeline", violations[0].annotation()
        )

    def test_reviewable_entry_carries_only_prose_and_unit(self):
        entry = guard.load_catalog(catalog(ENTRY), "head").entries[0]
        self.assertEqual(set(entry), {"name", "description", "documentation", "unit"})

    def test_kind_status_and_domain_are_machine_owned(self):
        after = (
            SIDECAR_ENTRY.replace("kind: scalar", "kind: vector")
            .replace("status: active", "status: draft")
            .replace("physics_domain: equilibrium", "physics_domain: transport")
        )
        self.assertEqual(
            {
                item.field
                for item in self.compare_sidecar(catalog(SIDECAR_ENTRY), catalog(after))
            },
            {"kind", "status", "physics_domain"},
        )

    def test_source_binding_and_link_fields_are_machine_owned(self):
        after = SIDECAR_ENTRY.replace("kind: imas-dd", "kind: signal")
        after = after.replace(
            "core_profiles/profiles_1d/electrons/density", "summary/local/density"
        )
        after = after.replace("version: 4.1.0", "version: 4.1.1")
        after = after.replace("links: []", "links:\n  - name:electron_temperature")
        self.assertEqual(
            {
                item.field
                for item in self.compare_sidecar(catalog(SIDECAR_ENTRY), catalog(after))
            },
            {"sources[0].kind", "sources[0].ref", "sources[0].version", "links"},
        )

    def test_generated_identity_roles_are_machine_owned(self):
        after = SIDECAR_ENTRY.replace(
            "operator_kind: population", "operator_kind: qualifier"
        )
        violations = self.compare_sidecar(catalog(SIDECAR_ENTRY), catalog(after))
        self.assertEqual(
            [item.field for item in violations], ["arguments[0].operator_kind"]
        )
        self.assertIn(
            "Data Dictionary or generated by the pipeline", violations[0].annotation()
        )

    def test_entry_removal_is_structural(self):
        violations = self.compare(catalog(ENTRY), "")
        self.assertEqual([item.field for item in violations], ["<entry-present>"])

    def test_entry_reordering_is_structural(self):
        violations = self.compare(
            catalog(ENTRY, SECOND_ENTRY), catalog(SECOND_ENTRY, ENTRY)
        )
        self.assertIn("<entry-order>", {item.field for item in violations})

    def test_removed_blank_line_is_structural(self):
        before = catalog(ENTRY, SECOND_ENTRY)
        after = before.replace(
            "unit: m^-3\n\n- name: electron_temperature",
            "unit: m^-3\n- name: electron_temperature",
            1,
        )
        violations = self.compare(before, after)
        self.assertEqual([item.field for item in violations], ["<entry-separation>"])

    def test_reordered_keys_are_structural(self):
        after = ENTRY.replace(
            "  description: Electron density.\n  documentation: Authored documentation.",
            "  documentation: Authored documentation.\n  description: Electron density.",
        )
        violations = self.compare(catalog(ENTRY), catalog(after))
        self.assertEqual([item.field for item in violations], ["<entry>.<key-order>"])


if __name__ == "__main__":
    unittest.main()
