from __future__ import annotations

import importlib.util
import subprocess
import sys
import unittest
from pathlib import Path
from unittest.mock import patch

MODULE_PATH = Path(__file__).with_name("review_edit_guard.py")
SPEC = importlib.util.spec_from_file_location("review_edit_guard", MODULE_PATH)
assert SPEC is not None and SPEC.loader is not None
guard = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = guard
SPEC.loader.exec_module(guard)


def catalog(*entries: str) -> str:
    return "\n\n".join(entry.strip() for entry in entries) + "\n"


ENTRY = """
- name: electron_density
  kind: scalar
  status: active
  description: Electron density.
  documentation: Authored documentation.
  unit: m^-3
  physics_domain: equilibrium
  links: []
  arguments:
  - name: density
    operator: electron
    operator_kind: population
  sources:
  - kind: imas-dd
    ref: core_profiles/profiles_1d/electrons/density
    version: 4.1.0
"""

SECOND_ENTRY = """
- name: electron_temperature
  kind: scalar
  status: active
  description: Electron temperature.
  documentation: Authored documentation.
  unit: eV
  physics_domain: equilibrium
  links: []
  sources:
  - kind: imas-dd
    ref: core_profiles/profiles_1d/electrons/temperature
    version: 4.1.0
"""


class ReviewEditGuardTests(unittest.TestCase):
    def compare(self, before: str, after: str):
        return guard.compare_catalogs(
            "standard_names/equilibrium.yml",
            guard.load_catalog(before, "base"),
            guard.load_catalog(after, "head"),
        )

    def test_authored_fields_may_change(self):
        after = ENTRY.replace("electron_density", "free_electron_density", 1)
        after = after.replace("Electron density.", "Free-electron density.")
        after = after.replace(
            "Authored documentation.", "Expanded authored documentation."
        )
        self.assertEqual(self.compare(catalog(ENTRY), catalog(after)), [])

    def test_new_entry_is_allowed(self):
        self.assertEqual(self.compare("", catalog(ENTRY)), [])

    def test_changed_catalog_paths_selects_yaml_below_standard_names(self):
        result = subprocess.CompletedProcess(
            args=[],
            returncode=0,
            stdout="standard_names/equilibrium.yml\nstandard_names/README.md\n",
            stderr="",
        )
        with patch.object(guard, "_git", return_value=result) as git:
            self.assertEqual(
                guard.changed_catalog_paths("base", "head"),
                ["standard_names/equilibrium.yml"],
            )
        self.assertEqual(git.call_args.args[-1], "standard_names")

    def test_unit_change_names_identity_field_and_values(self):
        violations = self.compare(
            catalog(ENTRY), catalog(ENTRY.replace("unit: m^-3", "unit: eV"))
        )
        self.assertEqual(
            [(item.identity, item.field, item.base, item.head) for item in violations],
            [("electron_density", "unit", "m^-3", "eV")],
        )
        self.assertIn(
            "Data Dictionary or generated by the pipeline", violations[0].annotation()
        )

    def test_kind_and_status_are_machine_owned(self):
        after = ENTRY.replace("kind: scalar", "kind: vector").replace(
            "status: active", "status: draft"
        )
        self.assertEqual(
            {item.field for item in self.compare(catalog(ENTRY), catalog(after))},
            {"kind", "status"},
        )

    def test_source_binding_fields_are_machine_owned(self):
        after = ENTRY.replace("kind: imas-dd", "kind: signal")
        after = after.replace(
            "core_profiles/profiles_1d/electrons/density", "summary/local/density"
        )
        after = after.replace("version: 4.1.0", "version: 4.1.1")
        self.assertEqual(
            {item.field for item in self.compare(catalog(ENTRY), catalog(after))},
            {"sources[0].kind", "sources[0].ref", "sources[0].version"},
        )

    def test_generated_identity_roles_are_machine_owned(self):
        after = ENTRY.replace("operator_kind: population", "operator_kind: qualifier")
        self.assertEqual(
            [item.field for item in self.compare(catalog(ENTRY), catalog(after))],
            ["arguments[0].operator_kind"],
        )

    def test_entry_removal_is_structural(self):
        violations = self.compare(catalog(ENTRY), "")
        self.assertEqual([item.field for item in violations], ["<entry-present>"])

    def test_entry_reordering_is_structural(self):
        violations = self.compare(
            catalog(ENTRY, SECOND_ENTRY), catalog(SECOND_ENTRY, ENTRY)
        )
        self.assertIn("<entry-order>", {item.field for item in violations})

    def test_removed_blank_line_is_structural(self):
        before = catalog(ENTRY, SECOND_ENTRY)
        after = before.replace(
            "version: 4.1.0\n\n- name: electron_temperature",
            "version: 4.1.0\n- name: electron_temperature",
            1,
        )
        violations = self.compare(before, after)
        self.assertEqual([item.field for item in violations], ["<entry-separation>"])

    def test_reordered_keys_are_structural(self):
        after = ENTRY.replace(
            "  kind: scalar\n  status: active", "  status: active\n  kind: scalar"
        )
        violations = self.compare(catalog(ENTRY), catalog(after))
        self.assertEqual([item.field for item in violations], ["<entry>.<key-order>"])


if __name__ == "__main__":
    unittest.main()
