site_name: "IMAS Standard Names Catalog"
site_url: !ENV [SITE_URL, "https://iterorganization.github.io/imas-standard-names-catalog/"]

plugins:
  - search
  - mike:
      canonical_version: latest
      version_selector: true
      css_dir: stylesheets
      javascript_dir: javascripts

nav:
  - Home: index.md
  - Catalog: catalog.md
  - Contributing: contributing.md

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - tables
  - attr_list

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
